/* This example requires Tailwind CSS v2.0+ */
import {
  AnnotationIcon,
  ClipboardListIcon,
  LightningBoltIcon,
  MailIcon,
} from '@heroicons/react/outline'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
  faPills,
  faClipboardList,
  faPrescriptionBottleMedical,
  faBookMedical,
  faMousePointer,
  faClinicMedical,
} from '@fortawesome/free-solid-svg-icons'

const priceGenius = [
  {
    id: 1,
    name: 'Insurance Information',
    description:
      'The first step to using PriceGenius is to select your insurance plan. This allows our code to access the insurance formulary and summary of benefits and coverage associated with your insurance plan',
    icon: faClipboardList,
  },
  {
    id: 2,
    name: 'Medication Selection',
    description:
      'Type in the prescription medication you want an estimate for. Be sure to select the correct strength, dosage form, and dosage route. Prices can vary with changes in these values, so be certain they match your prescription exactly',
    icon: faPills,
  },
  {
    id: 3,
    name: 'Medication Selection',
    description:
      'The final step to using PriceGenius is to select the appropriate pharmacy. Preferred pharmacies vary depending on the insurance company and there is usually a selection of preferred participating pharmacies available to choose from',
    icon: faClinicMedical,
  },
]
const planGenius = [
  {
    id: 1,
    name: 'Important Prescriptions',
    description:
      'Select up to 10 prescriptions important to your health. PlanGenius will use these medications as criteria for comparison to assist you in choosing an insurance plan',
    icon: faPrescriptionBottleMedical,
  },
  {
    id: 2,
    name: 'Plan Selection',
    description:
      'PlanGenius allows you to compare the details of up to 5 insurance plans at once. Select plans offered by your employer or allow PlanGenius to automatically generate the top 5 plans based on the selected medication',
    icon: faBookMedical,
  },
  {
    id: 3,
    name: 'Insurance Decision',
    description:
      'Based on the results generated by PlanGenius, you can make an educated decision for which insurance plan works best for you or your family’s budget',
    icon: faMousePointer,
  },
]

export default function Example() {
  return (
    <div className="overflow-hidden bg-gray-50 py-16 lg:py-24">
      <div className="relative mx-auto max-w-xl px-4 sm:px-6 lg:max-w-7xl lg:px-8">
        <svg
          className="absolute left-full hidden -translate-x-1/2 -translate-y-1/4 transform lg:block"
          width={404}
          height={784}
          fill="none"
          viewBox="0 0 404 784"
          aria-hidden="true"
        >
          <defs>
            <pattern
              id="b1e6e422-73f8-40a6-b5d9-c8586e37e0e7"
              x={0}
              y={0}
              width={20}
              height={20}
              patternUnits="userSpaceOnUse"
            >
              <rect
                x={0}
                y={0}
                width={4}
                height={4}
                className="text-gray-200"
                fill="currentColor"
              />
            </pattern>
          </defs>
          <rect
            width={404}
            height={784}
            fill="url(#b1e6e422-73f8-40a6-b5d9-c8586e37e0e7)"
          />
        </svg>

        <div className="relative">
          <h2 className="text-center text-3xl font-extrabold leading-8 tracking-tight text-gray-900 sm:text-4xl">
            The Tools to Take Control
          </h2>
          <p className="mx-auto mt-4 max-w-3xl text-center text-xl text-gray-500">
            Our goal at RxGenius is to ensure that every patient has access to
            the best healthcare tools available
          </p>
        </div>

        <div className="relative mt-12 lg:mt-24 lg:grid lg:grid-cols-2 lg:items-center lg:gap-8">
          <div className="relative">
            <img
              className=" rounded-lg drop-shadow-2xl	"
              width={200}
              src="https://rxgenius-media.s3.amazonaws.com/Price_Genius.png"
              alt=""
            />
            <p className="mt-3 text-lg text-gray-500">
              The cost of your prescription drugs with your insurance is just a
              few clicks away using our expertly coded PriceGenius tool
            </p>

            <dl className="mt-10 space-y-10">
              {priceGenius.map((item) => (
                <div key={item.id} className="relative">
                  <dt>
                    <div className="absolute flex h-12 w-12 items-center justify-center rounded-md bg-purple-600 text-white drop-shadow-2xl">
                      <FontAwesomeIcon
                        icon={item.icon}
                        size="lg"
                        aria-hidden="true"
                      />
                    </div>
                    <p className="ml-16 text-lg font-medium leading-6 text-gray-900">
                      {item.name}
                    </p>
                  </dt>
                  <dd className="mt-2 ml-16 text-base text-gray-500">
                    {item.description}
                  </dd>
                </div>
              ))}
            </dl>
          </div>

          <div className="relative -mx-4 mt-10 lg:mt-0" aria-hidden="true">
            <svg
              className="absolute left-1/2 -translate-x-1/2 translate-y-16 transform lg:hidden"
              width={784}
              height={404}
              fill="none"
              viewBox="0 0 784 404"
            >
              <defs>
                <pattern
                  id="ca9667ae-9f92-4be7-abcb-9e3d727f2941"
                  x={0}
                  y={0}
                  width={20}
                  height={20}
                  patternUnits="userSpaceOnUse"
                >
                  <rect
                    x={0}
                    y={0}
                    width={4}
                    height={4}
                    className="text-gray-200"
                    fill="currentColor"
                  />
                </pattern>
              </defs>
              <rect
                width={784}
                height={404}
                fill="url(#ca9667ae-9f92-4be7-abcb-9e3d727f2941)"
              />
            </svg>
            <img
              className="relative mx-auto rounded-lg bg-white	p-8 drop-shadow-2xl"
              width={490}
              src="https://rxgenius-media.s3.amazonaws.com/Select_Insurance.png"
              alt=""
            />
          </div>
        </div>

        <svg
          className="absolute right-full hidden translate-x-1/2 translate-y-12 transform lg:block"
          width={404}
          height={784}
          fill="none"
          viewBox="0 0 404 784"
          aria-hidden="true"
        >
          <defs>
            <pattern
              id="64e643ad-2176-4f86-b3d7-f2c5da3b6a6d"
              x={0}
              y={0}
              width={20}
              height={20}
              patternUnits="userSpaceOnUse"
            >
              <rect
                x={0}
                y={0}
                width={4}
                height={4}
                className="text-gray-200"
                fill="currentColor"
              />
            </pattern>
          </defs>
          <rect
            width={404}
            height={784}
            fill="url(#64e643ad-2176-4f86-b3d7-f2c5da3b6a6d)"
          />
        </svg>

        <div className="relative mt-12 sm:mt-16 lg:mt-24">
          <div className="lg:grid lg:grid-flow-row-dense lg:grid-cols-2 lg:items-center lg:gap-8">
            <div className="lg:col-start-2">
              <img
                className=" rounded-lg drop-shadow-2xl	"
                width={200}
                src="https://rxgenius-media.s3.amazonaws.com/PlanGenius.png"
                alt=""
              />
              <p className="mt-3 text-lg text-gray-500">
                Our PlanGenius tool allows you to compare insurance plans
                side-by-side to decide which plan best covers your medication{' '}
              </p>

              <dl className="mt-10 space-y-10">
                {planGenius.map((item) => (
                  <div key={item.id} className="relative">
                    <dt>
                      <div className="absolute flex h-12 w-12 items-center justify-center rounded-md bg-purple-600 text-white drop-shadow-2xl">
                        <FontAwesomeIcon
                          icon={item.icon}
                          size="lg"
                          aria-hidden="true"
                        />
                      </div>
                      <p className="ml-16 text-lg font-medium leading-6 text-gray-900">
                        {item.name}
                      </p>
                    </dt>
                    <dd className="mt-2 ml-16 text-base text-gray-500">
                      {item.description}
                    </dd>
                  </div>
                ))}
              </dl>
            </div>

            <div className="relative -mx-4 mt-10 lg:col-start-1 lg:mt-0">
              <svg
                className="absolute left-1/2 -translate-x-1/2 translate-y-16 transform lg:hidden"
                width={784}
                height={404}
                fill="none"
                viewBox="0 0 784 404"
                aria-hidden="true"
              >
                <defs>
                  <pattern
                    id="e80155a9-dfde-425a-b5ea-1f6fadd20131"
                    x={0}
                    y={0}
                    width={20}
                    height={20}
                    patternUnits="userSpaceOnUse"
                  >
                    <rect
                      x={0}
                      y={0}
                      width={4}
                      height={4}
                      className="text-gray-200"
                      fill="currentColor"
                    />
                  </pattern>
                </defs>
                <rect
                  width={784}
                  height={404}
                  fill="url(#e80155a9-dfde-425a-b5ea-1f6fadd20131)"
                />
              </svg>
              <img
                className="relative mx-auto rounded-lg bg-white	p-8 drop-shadow-2xl"
                width={490}
                src="https://rxgenius-media.s3.amazonaws.com/Select_Perscriptions.png"
                alt=""
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
